### ISSUE TITLE
assume 64-bit if not reported by `uname -m`

### ISSUE THREAD

**Issue by odisseus** [propensive/fury-old#1129]
```
2020-03-05.12:30:21.875 [info] 90700 Attempting to install ipfs for Mac OS X () to /Users/runner/.fury/usr/ipfs
2020-03-05.12:30:21.885 [fail] 00000 
2020-03-05.12:30:21.885 [fail] 00000 fury.model.UnknownOs
2020-03-05.12:30:21.885 [fail] 00000     at fury.core.IpfsSoftware$.$anonfun$tarGz$1(external.scala:201)
2020-03-05.12:30:21.885 [fail] 00000     at scala.util.Success.flatMap(Try.scala:251)
2020-03-05.12:30:21.885 [fail] 00000     at fury.core.IpfsSoftware$.tarGz(external.scala:196)
2020-03-05.12:30:21.885 [fail] 00000     at fury.core.Installable.install(external.scala:170)
2020-03-05.12:30:21.885 [fail] 00000     at fury.core.Installable.installedPath(external.scala:181)
2020-03-05.12:30:21.885 [fail] 00000     at fury.core.Ipfs$$anonfun$daemon$8.applyOrElse(external.scala:135)
2020-03-05.12:30:21.885 [fail] 00000     at fury.core.Ipfs$$anonfun$daemon$8.applyOrElse(external.scala:130)
2020-03-05.12:30:21.885 [fail] 00000     at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:38)
2020-03-05.12:30:21.885 [fail] 00000     at scala.util.Failure.recoverWith(Try.scala:236)
2020-03-05.12:30:21.885 [fail] 00000     at fury.core.Ipfs$.daemon(external.scala:130)
2020-03-05.12:30:21.885 [fail] 00000     at fury.core.Layer$.read(layer.scala:149)
2020-03-05.12:30:21.885 [fail] 00000     at fury.PermissionCli.$anonfun$grant$2(dependency.scala:366)
2020-03-05.12:30:21.885 [fail] 00000     at scala.util.Success.flatMap(Try.scala:251)
2020-03-05.12:30:21.885 [fail] 00000     at fury.PermissionCli.$anonfun$grant$1(dependency.scala:365)
2020-03-05.12:30:21.885 [fail] 00000     at scala.util.Success.flatMap(Try.scala:251)
2020-03-05.12:30:21.885 [fail] 00000     at fury.PermissionCli.grant(dependency.scala:364)
2020-03-05.12:30:21.885 [fail] 00000     at fury.FuryMenu$.$anonfun$menu$46(menu.scala:94)
2020-03-05.12:30:21.885 [fail] 00000     at fury.core.Menu.apply(structure.scala:69)
2020-03-05.12:30:21.885 [fail] 00000     at fury.core.Menu.apply(structure.scala:67)
2020-03-05.12:30:21.885 [fail] 00000     at fury.FuryServer$.invoke(main.scala:49)
2020-03-05.12:30:21.885 [fail] 00000     at fury.FuryServer$.$anonfun$run$2(main.scala:89)
2020-03-05.12:30:21.885 [fail] 00000     at fury.core.Lifecycle$.trackThread(lifecycle.scala:82)
2020-03-05.12:30:21.885 [fail] 00000     at fury.FuryServer$.run(main.scala:88)
2020-03-05.12:30:21.885 [fail] 00000     at fury.FuryServer$.nailMain(main.scala:73)
2020-03-05.12:30:21.885 [fail] 00000     at fury.FuryServer.nailMain(main.scala)
2020-03-05.12:30:21.885 [fail] 00000     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2020-03-05.12:30:21.885 [fail] 00000     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2020-03-05.12:30:21.885 [fail] 00000     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2020-03-05.12:30:21.885 [fail] 00000     at java.lang.reflect.Method.invoke(Method.java:498)
2020-03-05.12:30:21.885 [fail] 00000     at com.facebook.nailgun.NGSession.runImpl(NGSession.java:313)
2020-03-05.12:30:21.885 [fail] 00000     at com.facebook.nailgun.NGSession.run(NGSession.java:199)
```

**Comment by odisseus** [comment]
Bad:
```
Attempting to install ipfs for Mac OS X () to /Users/runner/.fury/usr/ipfs
```
Good:
```
Attempting to install ipfs for Mac OS X (64-bit x86) to /Users/runner/.fury/usr/ipfs
```

**Comment by propensive** [comment]
Do you think something changed in the GitHub environment to cause this? Fury just runs `uname` with some parameters to try to work out the system details.

**Comment by odisseus** [comment]
So it seems, and the worst thing is that sometimes this error doesn't happen.

**Comment by propensive** [comment]
That's terrible.

**Comment by propensive** [comment]
I think that we should assume the user is running on a 64-bit system if `uname -m` doesn't work.

**Comment by odisseus** [comment]
That's reasonable, but still I wonder what caused this issue in the first place. Basic applications like uname really shouldn't behave in unexpected ways.
