### ISSUE TITLE
upgrade to latest bloop launcher

### ISSUE THREAD

**Issue by ArturGajowy** [propensive/fury-old#120]
The install script outputs some WARN and some stacktrace on my machine (see below).
Otherwise the instalation seems to work.
Same thing happens if I run `sh fury-0.3.0.sh` instead of `bash fury-0.3.0.sh`.

```
artur@y510p:~$ bash fury-0.3.0.sh
     _____
    / ___/__ __ ____ __ __
   / __/ / // // ._// // /
  /_/    \_._//_/   \_. /
                   \___/

Fury build tool for Scala, version 0.3.0.
This software is provided under the Apache 2.0 License.
© Copyright 2018 Jon Pretty, Propensive Ltd.

This will install Fury on your computer.

Checking for dependencies...
 * Where should Fury be installed? [/home/artur/fury-0.3.0] 
 * Found Java version 1.8.0_191.
 * Installing Fury version 0.3.0...
bin/
bin/coursier
bin/launcher
bin/fury
bin/ng
etc/
etc/aliases
etc/completion/
etc/completion/zsh/
etc/completion/zsh/_fury
etc/completion/fish/
etc/completion/bash/
etc/zshrc
etc/bashrc
etc/fishrc
lib/
lib/fury.jar
lib/nailgun-server-1.0.0.jar
 * Installed Fury 0.3.0.
 * Launching Bloop version 1.2.1...
Starting the bsp launcher for bloop...
Jan 15, 2019 12:39:19 PM com.zaxxer.nuprocess.linux.LinuxProcess start
WARNING: Failed to start process
java.io.IOException: error=2, No such file or directory
	at com.zaxxer.nuprocess.internal.LibJava8.Java_java_lang_UNIXProcess_forkAndExec(Native Method)
	at com.zaxxer.nuprocess.linux.LinuxProcess.start(LinuxProcess.java:109)
	at com.zaxxer.nuprocess.linux.LinProcessFactory.createProcess(LinProcessFactory.java:40)
	at com.zaxxer.nuprocess.NuProcessBuilder.start(NuProcessBuilder.java:266)
	at bloop.launcher.core.Shell.runCommand(Shell.scala:87)
	at bloop.launcher.core.Shell.detectBloopInSystemPath(Shell.scala:153)
	at bloop.launcher.LauncherMain.detectServerState(Launcher.scala:232)
	at bloop.launcher.LauncherMain.connectToBloopBspServer(Launcher.scala:159)
	at bloop.launcher.LauncherMain.runLauncher(Launcher.scala:95)
	at bloop.launcher.LauncherMain.cli(Launcher.scala:78)
	at bloop.launcher.LauncherMain.main(Launcher.scala:59)
	at bloop.launcher.Launcher.main(Launcher.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at coursier.bootstrap.Bootstrap.main(Unknown Source)

A bloop installation has been detected either in the PATH or $HOME/.bloop

 * Launched Bloop 1.2.1.
Updating shell configuration
Backing up /home/artur/.bashrc as /home/artur/.bashrc.bak
Backing up /home/artur/.zshrc as /home/artur/.zshrc.bak

┌──────────────────────────────────────────────────────────────────┐
│ Fury is now installed. To start it, open a new terminal and run: │
│     fury start                                                   │
│                                                                  │
│ To check that Fury is working, run:                              │
│     fury about                                                   │
└──────────────────────────────────────────────────────────────────┘

artur@y510p:~$ 
```

**Comment by mzarnowski** [comment]
It should be fixed with new version of launcher: (https://github.com/scalacenter/bloop/pull/798)

**Comment by propensive** [comment]
Let's upgrade this. Seeing the stack trace isn't particularly great, either - I hope that's fixed in the new launcher, too.
