### ISSUE TITLE
Serialization of sorted sets is broken

### ISSUE THREAD

**Issue by odisseus** [propensive/fury-old#1202]
This is why integration tests fail with permission errors.

Aparently, this problem was [caused](https://github.com/propensive/fury/commit/d7e7d44ff60c97b8c156d59ba811acbf21950c08#diff-21de65a622bc41008e02fc83d48d3e67R85) by commit d7e7d44ff60c97b8c156d59ba811acbf21950c08.

Underlying exception ("Element id not found"):
```
fury.ogdl.OgdlException
	at fury.ogdl.Ogdl.selectDynamic(ogdl.scala:44)
	at fury.ogdl.OgdlWriter$.$anonfun$treeSet$2(ogdlwriter.scala:86)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
	at scala.collection.Iterator.foreach(Iterator.scala:941)
	at scala.collection.Iterator.foreach$(Iterator.scala:941)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
	at scala.collection.TraversableLike.map(TraversableLike.scala:238)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
	at fury.ogdl.OgdlWriter$.$anonfun$treeSet$1(ogdlwriter.scala:82)
	at fury.ogdl.Ogdl$.apply(ogdl.scala:68)
```

**Comment by propensive** [comment]
This probably relates not so much to Sorted Sets but to sorted sets of permissions. The OGDL serializer now needs to know the name of the field to use as the ID for each record, which is basically the index that's used to reference each entry. But it doesn't duplicate that entry inside the record any more.

It looks like this is using the default typeclass which assumes that the ID field is called "id". There will need to be a specific typeclass created in the companion object of the element type which specifies a different "key" to use.

Unfortunately, we require uniqueness in this key, so we may have to add it to the type, in which case, it's probably best to just add an `id` field to the case class.

**Comment by odisseus** [comment]
Actually, I got this stack trace while serializing a sorted set of strings.

**Comment by propensive** [comment]
Oh, well strings don't have `id` fields either.

I think the problem is the "catch-all" typeclass which just says "assume there's an ID field unless specified otherwise". It might make more sense to derive the default typeclass using Magnolia, based on the name of the first parameter. I can do this, if you like, but if you're already making progress this might be a good opportunity to learn what's going on here.

**Comment by odisseus** [comment]
This issue cannot be closed yet. I decided to close PR #1206, because it turned out to introduce new bugs along with fixing this particular one, and your recent merges don't seem to affect this issue.
