### ISSUE TITLE
tab completion on `dependency add` causes error

### ISSUE THREAD

**Issue by propensive** [propensive/fury-old#1222]
When typing,
```
fury dependency add -m<tab>
```
an error is reported.

The error is fine, but it shouldn't be printed at all, because the system should be in "completion" mode, which should mean that no output other than completions should be produced. I'm not sure why it is.

**Comment by odisseus** [comment]
```
_arguments:comparguments:325: invalid argument: The argument '' was not a valid value for the parameter '-m/--module'.
```

**Comment by odisseus** [comment]
Looks like this issue is caused by a bug somewhere else, probably in the code that handles command completions.

## Stack trace
```
An unexpected error occurred:
exoskeleton.InvalidArgValue: the value '-m/--module' is not valid for the parameter --
    at exoskeleton.ParamMap.get(parameters.scala:92)
    at fury.core.Cli.preview(cli.scala:184)
    at fury.DependencyCli.$anonfun$add$10(dependency.scala:102)
    at scala.util.Success.flatMap(Try.scala:251)
    at fury.DependencyCli.$anonfun$add$8(dependency.scala:101)
    at scala.util.Success.flatMap(Try.scala:251)
    at fury.DependencyCli.$anonfun$add$6(dependency.scala:100)
    at scala.util.Success.flatMap(Try.scala:251)
    at fury.DependencyCli.$anonfun$add$4(dependency.scala:99)
    at scala.util.Success.flatMap(Try.scala:251)
    at fury.DependencyCli.$anonfun$add$3(dependency.scala:98)
    at scala.util.Success.flatMap(Try.scala:251)
    at fury.DependencyCli.$anonfun$add$2(dependency.scala:97)
    at scala.util.Success.flatMap(Try.scala:251)
    at fury.DependencyCli.$anonfun$add$1(dependency.scala:96)
    at scala.util.Success.flatMap(Try.scala:251)
    at fury.DependencyCli.add(dependency.scala:95)
    at fury.FuryMenu$.$anonfun$menu$29(menu.scala:73)
    at fury.core.Menu.apply(structure.scala:82)
    at fury.core.Menu.apply(structure.scala:80)
    at fury.core.Cli$.asCompletion(cli.scala:101)
    at fury.FuryMenu$.$anonfun$menu$26(menu.scala:67)
    at fury.core.Menu.apply(structure.scala:82)
    at fury.FuryServer$.invoke(main.scala:49)
    at fury.FuryServer$.$anonfun$run$2(main.scala:92)
    at fury.core.Lifecycle$.trackThread(lifecycle.scala:82)
    at fury.FuryServer$.run(main.scala:91)
    at fury.FuryServer$.nailMain(main.scala:73)
    at fury.FuryServer.nailMain(main.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.facebook.nailgun.NGSession.runImpl(NGSession.java:313)
    at com.facebook.nailgun.NGSession.run(NGSession.java:199)
```

**Comment by odisseus** [comment]
The problem is caused by the fact that, in the command completion mode, the signal to [interrupt the execution](https://github.com/propensive/fury/blob/e3cc6242ea28bdb64a16cf2a72f84b1245f46070/src/core/cli.scala#L171) before doing actual work is just another exception. As a result, if any step in the for-comprehension returns a `Failure` before `cli.call()` is called, this would print an error message in the command completion mode.

Usually this situation is avoided by converting any steps that might fail into options, but, unfortunately, the information about the kind of failure (e. g. missing module name vs invalid module name vs name of a nonexistent module) gets lost.

**Comment by propensive** [comment]
Looks like it's working now.
