### ISSUE TITLE
Support for IPFS 0.6.x

### ISSUE THREAD

**Issue by odisseus** [propensive/fury-old#1283]
The latest version of IPFS allows to use its HTTP API only with the POST method (see https://github.com/ipfs/go-ipfs/pull/7097). Attempting to use current builds of Fury with this version of the IPFS daemon results in exceptions like this one:

```
An unexpected error occurred:
  java.lang.RuntimeException: IOException contacting IPFS daemon.
  Trailer: null 405 - Method Not Allowed
  
      at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1900)
      at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
      at io.ipfs.api.IPFS.get(IPFS.java:682)
      at io.ipfs.api.IPFS.retrieve(IPFS.java:675)
      at io.ipfs.api.IPFS.retrieveAndParse(IPFS.java:637)
      at io.ipfs.api.IPFS.version(IPFS.java:585)
      at io.ipfs.api.IPFS.<init>(IPFS.java:71)
      at io.ipfs.api.IPFS.<init>(IPFS.java:47)
```

This change doesn't require any changes in the Fury code, but the [java-ipfs-http-client](https://github.com/ipfs-shipyard/java-ipfs-http-client) library will have to be updated as soon as the new approach is implemented (see https://github.com/ipfs-shipyard/java-ipfs-http-client/issues/157).

**Comment by propensive** [comment]
It's been quite a while since the last release. I wonder if it fixes any other issues...

**Comment by odisseus** [comment]
Looks like there are no breaking changes between versions 0.5.1 and [0.6.0](https://github.com/ipfs/go-ipfs/releases/tag/v0.6.0).
