### ISSUE TITLE
Hints are broken for the module list command

### ISSUE THREAD

**Issue by odisseus** [propensive/fury-old#1483]
```
% fury module list -p fu[TAB]
_arguments:comparguments:325: invalid argument: ^[[2K^[[1mThe project has not been specified.^[[0m
```

Stack trace:
```
An unexpected error occurred:
fury.text.Unspecified
    at fury.text.Unspecified$.apply(strings.scala:59)
    at fury.text.package$OptionExtensions.asTry(strings.scala:50)
    at fury.ModuleCli.$anonfun$list$8(module.scala:93)
    at scala.util.Success.flatMap(Try.scala:251)
    at fury.ModuleCli.$anonfun$list$6(module.scala:92)
    at scala.util.Success.flatMap(Try.scala:251)
    at fury.ModuleCli.$anonfun$list$4(module.scala:91)
    at scala.util.Success.flatMap(Try.scala:251)
    at fury.ModuleCli.$anonfun$list$3(module.scala:90)
    at scala.util.Success.flatMap(Try.scala:251)
    at fury.ModuleCli.$anonfun$list$2(module.scala:89)
    at scala.util.Success.flatMap(Try.scala:251)
    at fury.ModuleCli.$anonfun$list$1(module.scala:88)
    at scala.util.Success.flatMap(Try.scala:251)
    at fury.ModuleCli.list(module.scala:87)
    at fury.FuryMenu$.$anonfun$menu$38(menu.scala:86)
    at fury.core.Menu.apply(structure.scala:82)
    at fury.core.Menu.apply(structure.scala:80)
    at fury.core.Cli$.asCompletion(cli.scala:107)
    at fury.FuryMenu$.$anonfun$menu$26(menu.scala:67)
    at fury.core.Menu.apply(structure.scala:82)
    at fury.FuryServer$.invoke(main.scala:49)
    at fury.FuryServer$.$anonfun$run$2(main.scala:83)
    at fury.core.Lifecycle$.trackThread(lifecycle.scala:80)
    at fury.FuryServer$.run(main.scala:82)
    at fury.FuryServer$.nailMain(main.scala:65)
    at fury.FuryServer.nailMain(main.scala)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    at com.facebook.nailgun.NGSession.runImpl(NGSession.java:313)
    at com.facebook.nailgun.NGSession.run(NGSession.java:199)

```

**Comment by propensive** [comment]
I guess this will be fixed when we update the `module` submenu.

**Comment by propensive** [comment]
Appears to work now.
