### ISSUE TITLE
shapeless compilation error with 2.13 (while following `getting-started` doc)

### ISSUE THREAD

**Issue by strobe** [propensive/fury-old#253]
I've followed `getting-started` guide with `fury-0.4.0` and got following error at end of `Supporting different compilers` section:

```
% fury build compile -s scala-2.13
 » scala/compiler   .   .  [*]
   » shapeless/gen         [!]
   └─» shapeless/core   .  [ ]

Output from shapeless/gen:
Compiling Lic4TYUHwPYKYv6QyUDhJg (1 Scala source)
Attempting to fetch ch.epfl.scala:compiler-bridge_2.13:1.2.1+106-0dad4a69.
[W] 	module not found: ch.epfl.scala#compiler-bridge_2.13;1.2.1+106-0dad4a69
[W] ==== local: tried
[W]   /Users/evgeniy/.ivy2/local/ch.epfl.scala/compiler-bridge_2.13/1.2.1+106-0dad4a69/ivys/ivy.xml
[W] ==== public: tried
[W]   https://repo1.maven.org/maven2/ch/epfl/scala/compiler-bridge_2.13/1.2.1+106-0dad4a69/compiler-bridge_2.13-1.2.1+106-0dad4a69.pom
[W] ==== sonatype-staging: tried
[W]   https://oss.sonatype.org/content/repositories/staging/ch/epfl/scala/compiler-bridge_2.13/1.2.1+106-0dad4a69/compiler-bridge_2.13-1.2.1+106-0dad4a69.pom
[W] 	::::::::::::::::::::::::::::::::::::::::::::::
[W] 	::          UNRESOLVED DEPENDENCIES         ::
[W] 	::::::::::::::::::::::::::::::::::::::::::::::
[W] 	:: ch.epfl.scala#compiler-bridge_2.13;1.2.1+106-0dad4a69: not found
[W] 	::::::::::::::::::::::::::::::::::::::::::::::
[W]
Compiled Lic4TYUHwPYKYv6QyUDhJg (15ms)
sbt.internal.inc.InvalidComponent: The compiler bridge sources ch.epfl.scala:compiler-bridge_2.13:1.2.1+106-0dad4a69:compile could not be retrieved.

	Note: Unresolved dependencies path:
		ch.epfl.scala:compiler-bridge_2.13:1.2.1+106-0dad4a69
		  +- org.scala-sbt.temp:temp-module-52f238aede5a1d8d7a484c2bec27a144810e2ac0:1.2.1+106-0dad4a69
	at sbt.internal.inc.ZincComponentCompiler.$anonfun$compileAndInstall$3(ZincComponentCompiler.scala:272)
	at sbt.internal.inc.ZincComponentCompiler.$anonfun$compileAndInstall$3$adapted(ZincComponentCompiler.scala:262)
	at sbt.io.IO$.withTemporaryDirectory(IO.scala:376)
	at sbt.io.IO$.withTemporaryDirectory(IO.scala:383)
	at sbt.internal.inc.ZincComponentCompiler.$anonfun$compileAndInstall$2(ZincComponentCompiler.scala:262)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at sbt.internal.util.BufferedLogger.bufferQuietly(BufferedLogger.scala:106)
	at sbt.internal.inc.ZincComponentCompiler.$anonfun$compileAndInstall$1(ZincComponentCompiler.scala:262)
	at sbt.internal.inc.ZincComponentCompiler.$anonfun$compileAndInstall$1$adapted(ZincComponentCompiler.scala:259)
	at sbt.io.IO$.withTemporaryDirectory(IO.scala:376)
	at sbt.io.IO$.withTemporaryDirectory(IO.scala:383)
	at sbt.internal.inc.ZincComponentCompiler.compileAndInstall(ZincComponentCompiler.scala:259)
	at sbt.internal.inc.ZincComponentCompiler.$anonfun$compiledBridgeJar$1(ZincComponentCompiler.scala:225)
	at sbt.internal.inc.IfMissing$Define.run(IfMissing.scala:19)
	at sbt.internal.inc.ZincComponentManager.createAndCache$1(ZincComponentManager.scala:46)
	at sbt.internal.inc.ZincComponentManager.$anonfun$files$3(ZincComponentManager.scala:57)
	at sbt.internal.inc.ZincComponentManager.getOrElse$1(ZincComponentManager.scala:38)
	at sbt.internal.inc.ZincComponentManager.$anonfun$files$2(ZincComponentManager.scala:57)
	at sbt.internal.inc.ZincComponentManager$$anon$1.call(ZincComponentManager.scala:87)
	at bloop.BloopComponentsLock$.apply(BloopComponentsLock.scala:9)
	at sbt.internal.inc.ZincComponentManager.lock(ZincComponentManager.scala:87)
	at sbt.internal.inc.ZincComponentManager.$anonfun$lockSecondaryCache$1(ZincComponentManager.scala:84)
	at scala.Option.map(Option.scala:146)
	at sbt.internal.inc.ZincComponentManager.lockSecondaryCache(ZincComponentManager.scala:82)
	at sbt.internal.inc.ZincComponentManager.fromSecondary$1(ZincComponentManager.scala:55)
	at sbt.internal.inc.ZincComponentManager.$anonfun$files$6(ZincComponentManager.scala:61)
	at sbt.internal.inc.ZincComponentManager.getOrElse$1(ZincComponentManager.scala:38)
	at sbt.internal.inc.ZincComponentManager.$anonfun$files$5(ZincComponentManager.scala:61)
	at sbt.internal.inc.ZincComponentManager$$anon$1.call(ZincComponentManager.scala:87)
	at bloop.BloopComponentsLock$.apply(BloopComponentsLock.scala:9)
	at sbt.internal.inc.ZincComponentManager.lock(ZincComponentManager.scala:87)
	at sbt.internal.inc.ZincComponentManager.lockLocalCache(ZincComponentManager.scala:78)
	at sbt.internal.inc.ZincComponentManager.files(ZincComponentManager.scala:61)
	at sbt.internal.inc.ZincComponentManager.file(ZincComponentManager.scala:66)
	at sbt.internal.inc.ZincComponentCompiler.compiledBridgeJar(ZincComponentCompiler.scala:225)
	at sbt.internal.inc.ZincComponentCompiler$ZincCompilerBridgeProvider.compiledBridge(ZincComponentCompiler.scala:83)
	at sbt.internal.inc.ZincComponentCompiler$ZincCompilerBridgeProvider.fetchCompiledBridge(ZincComponentCompiler.scala:90)
	at sbt.internal.inc.AnalyzingCompiler.loader(AnalyzingCompiler.scala:357)
	at sbt.internal.inc.AnalyzingCompiler.getInterfaceClass(AnalyzingCompiler.scala:375)
	at sbt.internal.inc.AnalyzingCompiler.call(AnalyzingCompiler.scala:342)
	at sbt.internal.inc.AnalyzingCompiler.newCachedCompiler(AnalyzingCompiler.scala:237)
	at sbt.internal.inc.AnalyzingCompiler.newCachedCompiler(AnalyzingCompiler.scala:224)
	at sbt.internal.inc.FreshCompilerCache.apply(CompilerCache.scala:79)
	at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:127)
	at sbt.internal.inc.bloop.internal.BloopHighLevelCompiler.compileSources$1(BloopHighLevelCompiler.scala:132)
	at sbt.internal.inc.bloop.internal.BloopHighLevelCompiler.$anonfun$compile$16(BloopHighLevelCompiler.scala:191)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at sbt.internal.inc.bloop.internal.BloopHighLevelCompiler.timed$1(BloopHighLevelCompiler.scala:69)
	at sbt.internal.inc.bloop.internal.BloopHighLevelCompiler.$anonfun$compile$15(BloopHighLevelCompiler.scala:191)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at monix.eval.internal.TaskRunLoop$.monix$eval$internal$TaskRunLoop$$loop$1(TaskRunLoop.scala:187)
	at monix.eval.internal.TaskRunLoop$RestartCallback$1.onSuccess(TaskRunLoop.scala:119)
	at monix.eval.Task$.$anonfun$forkedUnit$2(Task.scala:1463)
	at monix.execution.internal.forkJoin.AdaptedForkJoinTask.exec(AdaptedForkJoinTask.scala:27)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.pollAndExecAll(ForkJoinPool.java:1021)
	at java.util.concurrent.ForkJoinPool$WorkQueue.execLocalTasks(ForkJoinPool.java:1046)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1058)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Attempting to fetch ch.epfl.scala:compiler-bridge_2.13:1.2.1+106-0dad4a69.
[W] 	module not found: ch.epfl.scala#compiler-bridge_2.13;1.2.1+106-0dad4a69
[W] ==== local: tried
[W]   /Users/evgeniy/.ivy2/local/ch.epfl.scala/compiler-bridge_2.13/1.2.1+106-0dad4a69/ivys/ivy.xml
[W] ==== public: tried
[W]   https://repo1.maven.org/maven2/ch/epfl/scala/compiler-bridge_2.13/1.2.1+106-0dad4a69/compiler-bridge_2.13-1.2.1+106-0dad4a69.pom
[W] ==== sonatype-staging: tried
[W]   https://oss.sonatype.org/content/repositories/staging/ch/epfl/scala/compiler-bridge_2.13/1.2.1+106-0dad4a69/compiler-bridge_2.13-1.2.1+106-0dad4a69.pom
[W] 	::::::::::::::::::::::::::::::::::::::::::::::
[W] 	::          UNRESOLVED DEPENDENCIES         ::
[W] 	::::::::::::::::::::::::::::::::::::::::::::::
[W] 	:: ch.epfl.scala#compiler-bridge_2.13;1.2.1+106-0dad4a69: not found
[W] 	::::::::::::::::::::::::::::::::::::::::::::::
[W]
[E] The compiler bridge sources ch.epfl.scala:compiler-bridge_2.13:1.2.1+106-0dad4a69:compile could not be retrieved.
[E]
[E] 	Note: Unresolved dependencies path:
[E] 		ch.epfl.scala:compiler-bridge_2.13:1.2.1+106-0dad4a69
[E] 		  +- org.scala-sbt.temp:temp-module-52f238aede5a1d8d7a484c2bec27a144810e2ac0:1.2.1+106-0dad4a69
Total time: 390ms
```

Seems like it trying to get `compiler-bridge_2.13` but only `compiler-bridge_2.13.0-M2` is available 
at https://repo1.maven.org/maven2/ch/epfl/scala/ or at https://oss.sonatype.org/content/repositories/staging/ch/epfl/scala/

**Comment by propensive** [comment]
It looks like this is a problem with Bloop, as Rob Norris has experienced the same thing.

**Comment by propensive** [comment]
Thanks to a newly-published artifact, there is no longer a problem with resolving it. But it still doesn't compile correctly, so I'll keep this issue open until I have a chance to find out why.
