### ISSUE TITLE
check for cycles in dependencies

### ISSUE THREAD

**Issue by propensive** [propensive/fury-old#29]
There's nothing to stop users creating cycles between module dependencies. I've not tested this, but it probably creates a stack-overflow error.

**Comment by odisseus** [comment]
Confirmed `StackOverflowError` on Fury 0.6.7.
```
Exception in thread "main" java.lang.StackOverflowError
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at scala.util.Success.flatMap(Try.scala:251)
	at fury.core.Universe.dependencies(data.scala:831)
	at fury.core.Universe.$anonfun$dependencies$4(data.scala:834)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:237)
	at scala.collection.immutable.RedBlackTree$._foreachKey(RedBlackTree.scala:111)
	at scala.collection.immutable.RedBlackTree$.foreachKey(RedBlackTree.scala:107)
	at scala.collection.immutable.TreeSet.foreach(TreeSet.scala:154)
	at scala.collection.TraversableLike.map(TraversableLike.scala:237)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:230)
	at scala.collection.immutable.TreeSet.scala$collection$SetLike$$super$map(TreeSet.scala:53)
	at scala.collection.SetLike.map(SetLike.scala:104)
	at scala.collection.SetLike.map$(SetLike.scala:104)
	at scala.collection.immutable.TreeSet.map(TreeSet.scala:53)	
        ...
```
