### ISSUE TITLE
watcher causes `inotify` error sometimes

### ISSUE THREAD

**Issue by propensive** [propensive/fury-old#737]
When using the watcher to check for file changes, after a while, new instances throw an exception:
```
An unexpected error occurred:
java.io.IOException: User limit of inotify instances reached or too many open files
    at sun.nio.fs.LinuxWatchService.<init>(LinuxWatchService.java:64)
    at sun.nio.fs.LinuxFileSystem.newWatchService(LinuxFileSystem.java:47)
    at io.methvin.watcher.DirectoryWatcher$Builder.osDefaultWatchService(DirectoryWatcher.java:132)
    at io.methvin.watcher.DirectoryWatcher$Builder.build(DirectoryWatcher.java:112)
    at io.methvin.better.files.RecursiveFileMonitor.<init>(RecursiveFileMonitor.scala:78)
    at fury.SourceWatcher$$anon$1.<init>(rebuild.scala:69)
    at fury.SourceWatcher.$anonfun$watchers$1(rebuild.scala:69)
    at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:237)
    at scala.collection.immutable.HashSet$HashSet1.foreach(HashSet.scala:321)
    at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:977)
    at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:977)
    at scala.collection.TraversableLike.map(TraversableLike.scala:237)
    at scala.collection.TraversableLike.map$(TraversableLike.scala:230)
    at scala.collection.AbstractSet.scala$collection$SetLike$$super$map(Set.scala:51)
    at scala.collection.SetLike.map(SetLike.scala:104)
    at scala.collection.SetLike.map$(SetLike.scala:104)
    at scala.collection.AbstractSet.map(Set.scala:51)
    at fury.SourceWatcher.<init>(rebuild.scala:69)
    at fury.BuildCli$.$anonfun$compile$36(build.scala:210)
    at scala.util.Success.$anonfun$map$1(Try.scala:255)
    at scala.util.Success.map(Try.scala:213)
    at fury.BuildCli$.$anonfun$compile$35(build.scala:209)
    at scala.util.Success.flatMap(Try.scala:251)
    at fury.BuildCli$.$anonfun$compile$32(build.scala:206)
    at scala.util.Success.flatMap(Try.scala:251)
    at fury.BuildCli$.$anonfun$compile$31(build.scala:205)
    at scala.util.Success.flatMap(Try.scala:251)
    at fury.BuildCli$.$anonfun$compile$30(build.scala:204)
    at fury.BuildCli$.$anonfun$compile$30$adapted(build.scala:203)
    at scala.util.Success.flatMap(Try.scala:251)
    at fury.BuildCli$.$anonfun$compile$29(build.scala:203)
    at scala.util.Success.flatMap(Try.scala:251)
    at fury.BuildCli$.$anonfun$compile$27(build.scala:202)
    at scala.util.Success.flatMap(Try.scala:251)
    at fury.BuildCli$.$anonfun$compile$23(build.scala:201)
    at scala.util.Success.flatMap(Try.scala:251)
    at fury.BuildCli$.$anonfun$compile$22(build.scala:200)
    at scala.util.Success.flatMap(Try.scala:251)
    at fury.BuildCli$.$anonfun$compile$21(build.scala:199)
    at scala.util.Success.flatMap(Try.scala:251)
    at fury.BuildCli$.$anonfun$compile$18(build.scala:198)
    at scala.util.Success.flatMap(Try.scala:251)
    at fury.BuildCli$.$anonfun$compile$17(build.scala:197)
    at scala.util.Success.flatMap(Try.scala:251)
    at fury.BuildCli$.$anonfun$compile$16(build.scala:196)
    at scala.util.Success.flatMap(Try.scala:251)
    at fury.BuildCli$.$anonfun$compile$14(build.scala:195)
    at scala.util.Success.flatMap(Try.scala:251)
    at fury.BuildCli$.$anonfun$compile$12(build.scala:194)
    at scala.util.Success.flatMap(Try.scala:251)
    at fury.BuildCli$.$anonfun$compile$8(build.scala:193)
    at scala.util.Success.flatMap(Try.scala:251)
    at fury.BuildCli$.$anonfun$compile$7(build.scala:192)
    at scala.util.Success.flatMap(Try.scala:251)
    at fury.BuildCli$.$anonfun$compile$6(build.scala:191)
    at scala.util.Success.flatMap(Try.scala:251)
    at fury.BuildCli$.$anonfun$compile$5(build.scala:190)
    at scala.util.Success.flatMap(Try.scala:251)
    at fury.BuildCli$.$anonfun$compile$2(build.scala:189)
    at scala.util.Success.flatMap(Try.scala:251)
    at fury.BuildCli$.$anonfun$compile$1(build.scala:188)
    at scala.util.Success.flatMap(Try.scala:251)
    at fury.BuildCli$.compile(build.scala:187)
    at fury.FuryMenu$.$anonfun$menu$15(menu.scala:42)
    at scala.util.Success.flatMap(Try.scala:251)
    at fury.core.Menu.apply(structure.scala:61)
    at fury.core.Menu.apply(structure.scala:52)
    at fury.core.Menu.$anonfun$apply$2(structure.scala:59)
    at scala.util.Success.flatMap(Try.scala:251)
    at fury.core.Menu.apply(structure.scala:59)
    at fury.core.Menu.apply(structure.scala:52)
    at fury.Main$.invoke(main.scala:56)
    at fury.Main$.$anonfun$run$2(main.scala:92)
    at fury.core.Lifecycle$.trackThread(lifecycle.scala:54)
    at fury.Main$.run(main.scala:91)
    at fury.Main$.nailMain(main.scala:76)
    at fury.Main.nailMain(main.scala)
    at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.facebook.nailgun.NGSession.runImpl(NGSession.java:313)
    at com.facebook.nailgun.NGSession.run(NGSession.java:199)
```

**Comment by propensive** [comment]
The problem goes away if `/proc/sys/fs/inotify/max_queued_watches` is set high enough. We can read this (on Linux) and check it, and print out a warning if it's too low.
