### ISSUE TITLE
Layer extract into default location doesn't work on Mac OS

### ISSUE THREAD

**Issue by odisseus** [propensive/fury-old#746]
This is probably the cause behind failing Github Actions builds.
### Stack trace
```
$ fury standalone layer extract -f bootstrap/build.fury
Exception in thread "main" java.lang.ExceptionInInitializerError
	at fury.core.Log$.global(logging.scala:98)
	at fury.Main$.run(main.scala:89)
	at fury.Main$.main(main.scala:65)
	at fury.Main.main(main.scala)
Caused by: java.nio.file.FileAlreadyExistsException: /tmp
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:88)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:384)
	at java.nio.file.Files.createDirectory(Files.java:674)
	at java.nio.file.Files.createAndCheckIsDirectory(Files.java:781)
	at java.nio.file.Files.createDirectories(Files.java:727)
	at fury.io.Path.mkdir(path.scala:177)
	at fury.io.Path.extant(path.scala:104)
	at fury.model.Installation$.<init>(layout.scala:87)
	at fury.model.Installation$.<clinit>(layout.scala)
	... 4 more
```

**Comment by odisseus** [comment]
It seems that the [NIO method](https://docs.oracle.com/javase/8/docs/api/java/nio/file/Files.html#createDirectories-java.nio.file.Path-java.nio.file.attribute.FileAttribute...-) [doesn't work if](https://stackoverflow.com/a/53956506) [one of the directories](https://github.com/propensive/fury/blob/538318a0c44d51557b91496c4241c535586916e5/src/model/layout.scala#L60) [in the path](https://github.com/propensive/fury/blob/538318a0c44d51557b91496c4241c535586916e5/src/model/layout.scala#L87) [is actually a symlink](https://apple.stackexchange.com/questions/1043/why-is-tmp-a-symlink-to-private-tmp).
