### ISSUE TITLE
Error on the installation process

### ISSUE THREAD

**Issue by FabioPinheiro** [propensive/fury-old#779]
I was going to experiment Fury but I got the error on the installation process after calling `make`

I clone the fury master branch
`commit 8df8842aed7d7d033bf65edebd3cafa33fc57fca`

How can I debug and find out what is the error? I appreciate any help

```                                   
➜ make
mkdir -p dist/bundle/lib
mkdir -p opt
curl -C - -s -o opt/fury-0.7.14.sh "http://downloads.furore.dev/fury-0.7.14.sh"
sh opt/fury-0.7.14.sh opt/fury-0.7.14
     _____
    / ___/__ __ ____ __ __
   / __/ / // // ._// // /
  /_/    \_._//_/   \_. /
                   \___/

Fury build tool for Scala, version 0.7.14.
This software is provided under the Apache 2.0 License.
Copyright 2019 Jon Pretty, Propensive OÜ.

This will install Fury on your computer.

 * Installing Fury to opt/fury-0.7.14
 * Found Java version 11.0.5.
 * Installing Fury version 0.7.14...
 * Installed Fury 0.7.14.
 * Not updating shell configurations for batch-mode installation
 * Checking for currently-active Fury daemon...
touch opt/fury-0.7.14/bin/fury
mkdir -p bootstrap/bin
tar cvzf bootstrap/build.fury .focus.fury layers/*
.focus.fury
layers/0A24A1586682A39838622B66BACF81A3B51A7F3448371AB31B54B75DA12DCD28
layers/170FFB493AD839E66CD7F53CC22E808852B98777274C1F200EACE8BBA19AD952
layers/3D11B9BCF50FBE70B34AAA410734DA6667123A7B5BB96AAFC8F6E187FC10B031
layers/72BC2FA87BC7E554FABB094FF86E87B8C4FC8CC43DB9543C9986F46F82AB7E04
opt/fury-0.7.14/bin/fury layer extract -f bootstrap/build.fury
opt/fury-0.7.14/bin/fury permission grant --module frontend --project fury -P 729
make: *** [Makefile:83: dist/bundle/lib/fury-frontend.jar] Error 131
```
```
➜  echo $? #The makefile exit the error code 2
2
➜  opt/fury-0.7.14/bin/fury permission grant --module frontend --project fury -P 729
➜  echo $? #the above command finished with error code 131                                                                
131
➜  scalac --version
Scala compiler version 2.13.0-20190613-143643-unknown -- Copyright 2002-2019, LAMP/EPFL and Lightbend, Inc.
➜  java --version
openjdk 11.0.5 2019-10-15
OpenJDK Runtime Environment (build 11.0.5+10)
OpenJDK 64-Bit Server VM (build 11.0.5+10, mixed mode)
➜  uname -a
Linux fmgp 5.4.2-arch1-1 #1 SMP PREEMPT Thu, 05 Dec 2019 12:29:40 +0000 x86_64 GNU/Linu
```

**Comment by FabioPinheiro** [comment]
The error comes when calling the nailgun
If I use `USE_NG_PY=1` I also got the same error

```
➜  fury git:(master) ✗ /home/fabio/fury/opt/fury-0.7.14/bin/ng --nailgun-version 
NailGun client version 1.0.0
➜  /home/fabio/fury/opt/fury-0.7.14/bin/ng.py --nailgun-port 8462 fury.Main -- 23709 permission grant --module frontend --project fury -P 729
➜  echo $?                                                         
131
```

```
➜  fury git:(master) ✗ python2 --version
Python 2.7.17
➜  fury git:(master) ✗ python3 --version
Python 3.8.0
➜  fury git:(master) ✗ python --version 
Python 3.8.0
```

**Comment by odisseus** [comment]
Try modifying the makefile so that it invokes `fury standalone` everywhere instead of just `fury`. This will run Fury directly as a Java application, rather than hosted on the Nailgun server.

If the problem disappears, it must have been in your instance of Nailgun. If the commands keep failing, at least you will see the error messages or stack traces.

**Comment by FabioPinheiro** [comment]
Thanks, @odisseus.
Does this error makes sense or did I mess this up to the point I got this error?
I'm was using java 11 
```
➜  fury git:(master) ✗ make 
curl -C - -s -o opt/fury-0.7.14.sh "http://downloads.furore.dev/fury-0.7.14.sh"
tar cvzf bootstrap/build.fury .focus.fury layers/*
.focus.fury
layers/0A24A1586682A39838622B66BACF81A3B51A7F3448371AB31B54B75DA12DCD28
layers/35CBCAC1F1ABE37C110B2318A78072AACE50D1611BC65312236FB123E2C2C8FC
layers/72BC2FA87BC7E554FABB094FF86E87B8C4FC8CC43DB9543C9986F46F82AB7E04
layers/DA4B26041ADDDB769CBEC747A2149C551CF9415B5CED478E54DDF11ABF650CD5
opt/fury-0.7.14/bin/fury layer extract -f bootstrap/build.fury
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
	at gastronomy.ByteEncoder$.$anonfun$hex$1(digest.scala:161)
	at gastronomy.Bytes.encoded(digest.scala:149)
	at gastronomy.Digest$.encoded$extension(digest.scala:54)
	at fury.model.Permission.hash(ids.scala:215)
	at fury.Recovery$.$anonfun$recover$4(recovery.scala:61)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:237)
	at scala.collection.immutable.HashSet$HashSet1.foreach(HashSet.scala:321)
	at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:977)
	at scala.collection.TraversableLike.map(TraversableLike.scala:237)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:230)
	at scala.collection.AbstractSet.scala$collection$SetLike$$super$map(Set.scala:51)
	at scala.collection.SetLike.map(SetLike.scala:104)
	at scala.collection.SetLike.map$(SetLike.scala:104)
	at scala.collection.AbstractSet.map(Set.scala:51)
	at fury.Recovery$.recover(recovery.scala:61)
	at fury.Main$.invoke(main.scala:56)
	at fury.Main$.$anonfun$run$2(main.scala:92)
	at fury.core.Lifecycle$.trackThread(lifecycle.scala:54)
	at fury.Main$.run(main.scala:91)
	at fury.Main$.main(main.scala:65)
	at fury.Main.main(main.scala)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 21 more
make: *** [Makefile:82: dist/bundle/lib/fury-frontend.jar] Error 1
```

With java version 8 I got:
```
➜  fury git:(master) ✗ make
curl -C - -s -o opt/fury-0.7.14.sh "http://downloads.furore.dev/fury-0.7.14.sh"
tar cvzf bootstrap/build.fury .focus.fury layers/*
.focus.fury
layers/0A24A1586682A39838622B66BACF81A3B51A7F3448371AB31B54B75DA12DCD28
layers/35CBCAC1F1ABE37C110B2318A78072AACE50D1611BC65312236FB123E2C2C8FC
layers/72BC2FA87BC7E554FABB094FF86E87B8C4FC8CC43DB9543C9986F46F82AB7E04
layers/DA4B26041ADDDB769CBEC747A2149C551CF9415B5CED478E54DDF11ABF650CD5
opt/fury-0.7.14/bin/fury layer extract -f bootstrap/build.fury
The following permissions are required to run the build:
HASH  CLASS                         TARGET                  ACTION    
4a8   java.lang.RuntimePermission   getenv.HOME             -         
c0d   java.lang.RuntimePermission   getenv.XDG_CONFIG_HOME  -         
c2e   java.lang.RuntimePermission   getenv.XDG_CONFIG_DIRS  -         
f90   java.lang.RuntimePermission   getenv.XDG_DATA_DIRS    -         
b7a   java.util.PropertyPermission  scala.*                 read      
7f0   java.lang.RuntimePermission   getenv.XDG_DATA_HOME    -         
538   java.lang.RuntimePermission   getenv.XDG_RUNTIME_DIR  -         
228   java.lang.RuntimePermission   getenv.XDG_CACHE_HOME   -         
00b   java.io.FilePermission        <<ALL FILES>>           read,write
You can grant these permissions with,

  fury permission grant -P <permission hash>

make: *** [Makefile:82: dist/bundle/lib/fury-frontend.jar] Error 1
```

**Comment by FabioPinheiro** [comment]
At this point I feel:
- Debugging this was not very intuitive:
- - the nailgun should print the error to the stdout when calling make
- - using fury standalone should be an option 
- Recovery from the error `NoPermissions` is not unsupported on java 11
- I don't understand this table and what I need todo. I would appreciate any help here

**Comment by odisseus** [comment]
At the moment Fury doesn't support Java 11, so it's no wonder you got an exception.

The Java 8 log seems in order. Fury enables the user to download any code form the network and execute it immediately, so we attempt to limit the threat by running that code with the [security manager](https://docs.oracle.com/javase/tutorial/essential/environment/security.html) enabled.

Fury also allows the build modules that need to run code (e. g. code generation or  tests) to declare required permissions. Such module will not be executed, unless all these permissions are granted by user.

Normally if you see a table like this one, it means that you're trying to build a module which doesn't have all required permissions. You could grant them all by executing a command like this one:
```
fury permission grant -P 4a8 c0d c2e f90  b7a 7f0 538 228 00b 
```
However, these permissions are checked at a much later stage than extracting a packaged layer (which is what line 82 does). 

Did you run `make clean` before `make`? Permission checking might have been triggered by the remains of your previous build attempt (although if it is indeed so, that's a bug).

**Comment by FabioPinheiro** [comment]
`fury permission grant -P 4a8 c0d c2e f90  b7a 7f0 538 228 00b`

GIve some errors with `b7a`

> Did you run make clean before make?

Not the first time. But I was also using JAVA 11
I need a bunch of clean retries: cloning and compiling...
I also did set the JAVA_HOME on my last try
At this point, I don't know what some of the problem

Thank you @odisseus for all the help

So I'm closing this ticket now and I'm going to play a bit with the fury build tool.
It would be nice to have some more update information on the web page.
Is there any particular reason why Java 11 is not supported at this time or it's just a question of manpower?
