### ISSUE TITLE
Adding a local directory to sources may take about a minute

### ISSUE THREAD

**Issue by odisseus** [propensive/fury-old#795]
It seems that Fury performs a Git clone even if the directory is local and empty.

## Call stack

```
 java.lang.Thread.State: RUNNABLE
        at java.io.FileInputStream.readBytes(Native Method)
        at java.io.FileInputStream.read(FileInputStream.java:255)
        at java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
        - locked <0x00000007457f97f0> (a java.lang.UNIXProcess$ProcessPipeInputStream)
        at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
        at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
        at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
        - locked <0x00000007457fdb38> (a java.io.InputStreamReader)
        at java.io.InputStreamReader.read(InputStreamReader.java:184)
        at java.io.BufferedReader.read1(BufferedReader.java:210)
        at java.io.BufferedReader.read(BufferedReader.java:286)
        - locked <0x00000007457fdb38> (a java.io.InputStreamReader)
        at java.io.Reader.read(Reader.java:140)
        at scala.io.BufferedSource.mkString(BufferedSource.scala:98)
        at guillotine.Executor$.guillotine$Executor$$$anonfun$string$1(macros.scala:95)
        at guillotine.Executor$$anonfun$2.exec(macros.scala:86)
        at guillotine.Executor$$anonfun$2.exec(macros.scala:86)
        at guillotine.Executor$.guillotine$Executor$$$anonfun$scalaUtilTry$1(macros.scala:74)
        at guillotine.Executor$$anonfun$1.exec(macros.scala:71)
        at guillotine.Executor$$anonfun$1.exec(macros.scala:71)
        at guillotine.package$Command.exec(macros.scala:160)
        at fury.core.Shell$git$.cloneBare(shell.scala:85)
        at fury.core.Repo.fetch(data.scala:726)
        at fury.core.SourceRepo.$anonfun$listFiles$2(data.scala:672)
        at fury.core.SourceRepo$$Lambda$885/311236318.apply(Unknown Source)
        at scala.Option.getOrElse(Option.scala:138)
        at fury.core.SourceRepo.listFiles(data.scala:672)
        at fury.core.SourceRepo.sourceCandidates(data.scala:698)
        at fury.SourceCli$.$anonfun$add$4(source.scala:109)
        at fury.SourceCli$$$Lambda$882/662628993.apply(Unknown Source)
        at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:237)
        at scala.collection.TraversableLike$$Lambda$12/2052078565.apply(Unknown Source)
        at scala.collection.immutable.RedBlackTree$._foreachKey(RedBlackTree.scala:111)
        at scala.collection.immutable.RedBlackTree$.foreachKey(RedBlackTree.scala:107)
        at scala.collection.immutable.TreeSet.foreach(TreeSet.scala:154)
        at scala.collection.TraversableLike.map(TraversableLike.scala:237)
        at scala.collection.TraversableLike.map$(TraversableLike.scala:230)
        at scala.collection.immutable.TreeSet.scala$collection$SetLike$$super$map(TreeSet.scala:53)
        at scala.collection.SetLike.map(SetLike.scala:104)
        at scala.collection.SetLike.map$(SetLike.scala:104)
        at scala.collection.immutable.TreeSet.map(TreeSet.scala:53)
        at fury.SourceCli$.$anonfun$add$3(source.scala:109)
        at fury.SourceCli$$$Lambda$881/1401152423.apply(Unknown Source)
        at scala.collection.immutable.List.flatMap(List.scala:338)
        at fury.SourceCli$.$anonfun$add$2(source.scala:108)
        at fury.SourceCli$$$Lambda$880/1505029630.apply(Unknown Source)
        at scala.util.Success.flatMap(Try.scala:251)
        at fury.SourceCli$.add(source.scala:106)
        at fury.FuryMenu$.$anonfun$menu$68(menu.scala:104)
        at fury.FuryMenu$$$Lambda$623/1478089369.apply(Unknown Source)
        at scala.util.Success.flatMap(Try.scala:251)
        at fury.core.Menu.apply(structure.scala:58)
        at fury.core.Menu.$anonfun$apply$2(structure.scala:56)
        at fury.core.Menu$$Lambda$655/1555379908.apply(Unknown Source)
        at scala.util.Success.flatMap(Try.scala:251)
        at fury.core.Menu.apply(structure.scala:56)
        at fury.Main$.invoke(main.scala:56)
        at fury.Main$.$anonfun$run$2(main.scala:92)
        at fury.Main$$$Lambda$61/1772507705.apply$mcI$sp(Unknown Source)
        at fury.core.Lifecycle$.trackThread(lifecycle.scala:54)
        at fury.Main$.run(main.scala:91)
        at fury.Main$.nailMain(main.scala:76)
        at fury.Main.nailMain(main.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.facebook.nailgun.NGSession.runImpl(NGSession.java:313)
        at com.facebook.nailgun.NGSession.run(NGSession.java:199)
```

**Comment by propensive** [comment]
@odisseus Can we repeat this? I don't think I've ever seen it...

**Comment by propensive** [comment]
@odisseus I've assigned this to you to either fix, or just close if it's not an issue any more.

**Comment by odisseus** [comment]
I don't remember anymore how to reproduce this issue, and the code that handles Git commands has been refactored several times since then, so I'll just close it.
