### ISSUE TITLE
repeated layer share times out

### ISSUE THREAD

**Issue by odisseus** [propensive/fury-old#881]
## Steps to reproduce
1. Check out any Fury project, e. g. Fury itself, and open a console in the checkout directory
2. `fury layer share`
3. `fury layer share`

### Expected behaviour
The share command succeeds both times

### Actual behaviour
The second invocation of `layer share` times out after 120 seconds.

#### Stack trace
```
java.util.concurrent.TimeoutException: Futures timed out after [120 seconds]
    at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:259)
    at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:263)
    at scala.concurrent.Await$.$anonfun$result$1(package.scala:219)
    at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:57)
    at scala.concurrent.Await$.result(package.scala:146)
    at fury.core.Ipfs$.daemon(ipfs.scala:102)
    at fury.core.Layer$.$anonfun$share$8(layer.scala:72)
    at scala.util.Success.flatMap(Try.scala:251)
    at fury.core.Layer$.$anonfun$share$6(layer.scala:71)
    at scala.util.Success.flatMap(Try.scala:251)
    at fury.core.Layer$.$anonfun$share$3(layer.scala:66)
    at scala.util.Success.flatMap(Try.scala:251)
    at fury.core.Layer$.$anonfun$share$1(layer.scala:64)
    at fury.model.Installation$.$anonfun$tmpDir$1(layout.scala:136)
    at fury.model.Installation$.tmpFile(layout.scala:142)
    at fury.model.Installation$.tmpDir(layout.scala:134)
    at fury.core.Layer$.share(layer.scala:63)
    at fury.LayerCli$.$anonfun$share$5(build.scala:600)
    at fury.LayerCli$.$anonfun$share$5$adapted(build.scala:599)
    at scala.util.Success.flatMap(Try.scala:251)
    at fury.LayerCli$.$anonfun$share$4(build.scala:599)
    at scala.util.Success.flatMap(Try.scala:251)
    at fury.LayerCli$.$anonfun$share$3(build.scala:598)
    at scala.util.Success.flatMap(Try.scala:251)
    at fury.LayerCli$.$anonfun$share$2(build.scala:597)
    at scala.util.Success.flatMap(Try.scala:251)
    at fury.LayerCli$.$anonfun$share$1(build.scala:596)
    at scala.util.Success.flatMap(Try.scala:251)
    at fury.LayerCli$.share(build.scala:595)
    at fury.FuryMenu$.$anonfun$menu$101(menu.scala:143)
    at scala.util.Success.flatMap(Try.scala:251)
    at fury.core.Menu.apply(structure.scala:66)
    at fury.core.Menu.$anonfun$apply$5(structure.scala:64)
    at scala.util.Success.flatMap(Try.scala:251)
    at fury.core.Menu.apply(structure.scala:64)
    at fury.Main$.invoke(main.scala:56)
    at fury.Main$.$anonfun$run$2(main.scala:92)
    at fury.core.Lifecycle$.trackThread(lifecycle.scala:54)
    at fury.Main$.run(main.scala:91)
    at fury.Main$.nailMain(main.scala:76)
    at fury.Main.nailMain(main.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.facebook.nailgun.NGSession.runImpl(NGSession.java:313)
    at com.facebook.nailgun.NGSession.run(NGSession.java:199)
```

### Environment
```
go-ipfs version: 0.5.0-dev-e27416992
Repo version: 7
System version: amd64/linux
Golang version: go1.13.4
```

## Notes
* Repeater layer share succeeds if the IPFS daemon is killed after each invocation.
* First layer share times out as well if the IPFS daemon is already running.
* This issue was probably introduced by PR #813.

**Comment by propensive** [comment]
I think you're right about it being #813. The automatic installation of IPFS has problems anyway on my laptop (WSL2) so this needs a bit more work...

**Comment by propensive** [comment]
I'm not able to repeat this. Does the `ipfs` command exist on your `PATH`?

**Comment by odisseus** [comment]
Yes, it does.

Interestingly, I couldn't reproduce this issue on my laptop.
```
go-ipfs version: 0.4.22-4e981576b-dirty
Repo version: 7
System version: amd64/linux
Golang version: go1.12.8

```
